FROM ubuntu:18.04

MAINTAINER Yaheng Wang(jjbioinfo@163.com)

ENV DEBIAN_FRONTEND noninteractive

# 国内跟换阿里镜像源
RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/mirrors.aliyun.com\/ubuntu\//g' /etc/apt/sources.list \
&& apt-get update

RUN apt-get install -y unzip \
		curl \
		cpanminus \
		openjdk-8-jre


# 安装fastqc
ENV FASTQC_VERSION=0.11.9

RUN curl -L http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FASTQC_VERSION}.zip -o /tmp/v${FASTQC_VERSION}.zip

WORKDIR /opt/software

RUN unzip /tmp/v${FASTQC_VERSION}.zip \
&& chmod 755 /opt/software/FastQC/fastqc

ENV PATH $PATH:/opt/software/FastQC
