FROM ubuntu:18.04

MAINTAINER Yaheng Wang(jjbioinfo@163.com)

ENV DEBIAN_FRONTEND noninteractive

# 国内跟换阿里镜像源
RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/mirrors.aliyun.com\/ubuntu\//g' /etc/apt/sources.list \
&& apt-get update

RUN apt-get install -y git \
		openjdk-8-jdk \
		make


# 安装trimmomatic
RUN cd /tmp \
&& git clone https://github.com/timflutre/trimmomatic.git

RUN cd /tmp/trimmomatic \
&& make \
&& mkdir -p /opt/software/jar \
&& mv /tmp/trimmomatic/classes/trimmomatic.jar /opt/software/jar
