FROM ubuntu:18.04

MAINTAINER Yaheng Wang(jjbioinfo@163.com)

ENV DEBIAN_FRONTEND noninteractive

# 国内跟换阿里镜像源
RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/mirrors.aliyun.com\/ubuntu\//g' /etc/apt/sources.list \
&& apt-get update

RUN apt-get install -y curl 
		


# 安装Minimap2
ENV MINIMAP2_VERSION=2.17

WORKDIR /tmp

RUN curl -L https://github.com/lh3/minimap2/releases/download/v${MINIMAP2_VERSION}/minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2 -o /tmp/minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2

RUN tar -jxvf /tmp/minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2 \
&& mv /tmp/minimap2-${MINIMAP2_VERSION}_x64-linux/minimap2 /usr/local/bin

RUN chmod 755 /usr/local/bin/minimap2 
